export const TYPES = {
    DataSource: Symbol.for('DataSource'),
    MarketplaceService: Symbol.for('MarketplaceService'),
    AddonJob: Symbol.for('AddonJob'),
    AddonService: Symbol.for('AddonService'),
    TransactionJob: Symbol.for('TransactionJob'),
    LicenseJob: Symbol.for('LicenseJob'),
    PricingJob: Symbol.for('PricingJob'),
    PricingService: Symbol.for('PricingService'),
    ValidationJob: Symbol.for('ValidationJob'),
    PriceCalculatorService: Symbol.for('PriceCalculatorService'),
    IgnoredFieldService: Symbol.for('IgnoredFieldService'),
    TransactionDao: Symbol.for('TransactionDao'),
    TransactionReconcileDao: Symbol.for('TransactionReconcileDao'),
    LicenseDao: Symbol.for('LicenseDao'),
    TransactionAdjustmentDao: Symbol.for('TransactionAdjustmentDao'),
    TransactionVersionDao: Symbol.for('TransactionVersionDao'),
    ResellerDao: Symbol.for('ResellerDao'),
    PreviousTransactionService: Symbol.for('PreviousTransactionService')
};